### ISSUE TITLE
Permanently modify referral rate for selected affiliate accounts.

### ISSUE THREAD

**Issue by nueverest** [AffiliateWP/affiliatewp-code-snippet-library#22]
I have filtration code below.  However, this filter only changes the referral rate during a transaction.  If an Admin goes to the backend and looks at the users account their affiliate rate is 15% instead of 25%.  This is confusing our admins and reducing trust in the plugin.

How do I change the referral rate automatically during the registration process so that this filter code is unnecessary?

```
/*
Give business affiliates a 25% commission for each product.
They must have an EIN or Foreign Equivalent.
Reference:
https://github.com/AffiliateWP/affiliatewp-code-snippet-library/blob/master/referrals/modify-first-referral-commission-amount.php
 */
function affwp_business_affiliate_commission ( $referral_amount, $affiliate_id, $amount, $reference, $product_id ) {
    $user_id = affwp_get_affiliate_user_id( $affiliate_id );
    $ein = get_the_author_meta( 'ein', $user_id );
    $foreignId = get_the_author_meta( 'foreignId', $user_id );

    // Check for an EIN or Foreign Id and give 25% Commision
    if ( (!empty($ein) && preg_match('/^(0[1-9]|[1-9]\d)-?\d{7}$/', $ein)) || !empty($foreignId) ) {
       $referral_amount = $amount * 0.25;
    }

    return $referral_amount;
}
add_filter( 'affwp_calc_referral_amount', 'affwp_business_affiliate_commission', 10, 5 );
```

**Comment by sumobi** [comment]
Hi @nueverest!

It sounds like you're wanting to automatically adjust the commission rate for specific affiliates when they register, based on some usermeta. For that, see this action hook: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/class-register.php#L362

Note, this is only a repo to house custom code snippets for AffiliateWP, we're not able to help you with your custom code. If you need developer assistance please get in touch with a consultant: https://affiliatewp.com/consultants/
