### ISSUE TITLE
Snippet not working!

### ISSUE THREAD

**Issue by ehsanmn67** [AffiliateWP/affiliatewp-code-snippet-library#23]
I'm setting up AffiliateWp for a client and we want to [Disable Affiliate To Affiliate Referrals](https://github.com/AffiliateWP/affiliatewp-code-snippet-library/blob/master/referrals/disable-affiliate-to-affiliate-referrals.php). The snippet is installed as a plugin but it seems not to be working and affiliates still get credit for referring another affiliate. Any thoughts?

**Comment by amdrew** [comment]
@ehsanmn67 I've tested and it's working fine for me. If an affiliate refers another affiliate and that affiliate purchases, a `0.00` referral is created. Is the affiliate who purchases logged in as a user (and thus an affiliate)? Perhaps that's why.

**Comment by ehsanmn67** [comment]
yes I'm pretty sure users were logged in. I ran another test just now with two new users, both signed up for affiliates, both signed in before checkout, and tried it both ways. They both got credit for referrals. I disabled all other plugins and tried it again and it still didn't work. I can't figure out what is causing this!

**Comment by amdrew** [comment]
@ehsanmn67 Please open a ticket on our support page and we'll resolve this issue for you: https://affiliatewp.com/support/

We'll require admin access and the 2 order numbers that generated the referrals.
