### ISSUE TITLE
Image upload as custom dashboard field

### ISSUE THREAD

**Issue by gangesh** [AffiliateWP/affiliatewp-code-snippet-library#29]
I used custom registration snippet, which worked great!
Now I need to add image upload field. 
I tried and in response I received image name in "$data" variable, which is not enough for "media_handle_upload" function. It required "$_FILES" data. 

Anyone faced similar issue or have a solution? 
Thanks in advance

**Comment by michaelbeil** [comment]
For any support-related questions, we ask that you send a ticket to https://affiliatewp.com/support as we reserve this repository for development purposes.
