### ISSUE TITLE
Limiting number of commissions per affiliate per person they refer

### ISSUE THREAD

**Issue by PaulKaan** [AffiliateWP/affiliatewp-code-snippet-library#30]
This is the next step to the snippet that allows you to limit the number of referrals an affiliate can receive.

The purpose is to limit the number of referrals so that the affiliate can only receive a commission on the first purchase made by the person they have referred. 

They should still be able to refer an unlimited number of people and receive commissions on the 1st purchase (or specified number of purchase) each person makes.

One option may be to use the Lifetime Commissions addon to limit this to a number of commissions for all of the affiliates lifetime customers.

**Comment by michaelbeil** [comment]
Thanks for the suggestion! We are actually looking to include this in a future version of AffiliateWP. I have no ETA on when this will be available. Therefore, I am going to close this issue.

If you have any support-related questions, we ask that you send a ticket to https://affiliatewp.com/support as we reserve this repository for development purposes.

**Comment by PaulKaan** [comment]
Thanks for the update Michael. Is there a link to the feature so I can subscribe and get a notification when it progresses?

**Comment by michaelbeil** [comment]
There is not a link available to this feature as our repository is private, so you cannot subscribe and get a notification when this progresses. We do not have an ETA on _when or if_ this feature will be out either in AffiliateWP or as an add-on. I have made a note to get in touch with you, connected with your support ticket with Ginger, _if_ such a feature is released in the future.
